---

- name: Test lookups
  hosts: cisco5
  gather_facts: False
  vars:
    fsm_template: "cisco_ios_show_ip_interface_brief.template"

  tasks:
    - name: Executing command
      cisco.ios.ios_command:
        commands: show ip int brief
      register: output

    - ansible.builtin.set_fact:
        show_ip: "{{ output.stdout[0] | parse_cli_textfsm(fsm_template) }}"

    - ansible.builtin.debug:
        msg: "{{ show_ip }}"

    - ansible.builtin.debug:
        msg: "{{ show_ip  | map(attribute='INTF') | list }}"
