---
- name: Transfer image file
  hosts: do_not_run_this_playbook
  tasks:
    - ansible.builtin.debug:
        var: ansible_facts
      when: ansible_facts.net_model == "C1111-4P"

    - ansible.builtin.debug:
        msg: "bootflash:/{{ os_image_file }}"

    - name: Transfer image file
      vars:
        # Hopefully 6 hours is enough
        ansible_command_timeout: 21600
      ansible.netcommon.net_put:
        src: "{{ os_image_file }}"
        dest: "bootflash:/{{ os_image_file }}"
        protocol: scp
      when: ansible_facts.net_model == "C1111-4P"
