---
- name: Global configuration
  hosts: cisco:arista:nxos:juniper
  gather_facts: True
  tasks:
    - name: Global config
      ansible.builtin.set_fact:
        config: "{{ lookup('template', 'templates/{{ ansible_network_os }}/global.j2') }}"

    - name: View the generated configuration
      ansible.builtin.debug:
        var: config.splitlines()

    - name: Global config (IOS)
      cisco.ios.ios_config:
        lines: "{{ config.splitlines() }}"
      when: ansible_network_os == 'ios'

    - name: Global config (EOS)
      arista.eos.eos_config:
        lines: "{{ config.splitlines() }}"
      when: ansible_network_os == 'eos'

    - name: Global config (NX-OS)
      cisco.nxos.nxos_config:
        lines: "{{ config.splitlines() }}"
      when: ansible_network_os == 'nxos'

    - name: Global config (Junos)
      junipernetworks.junos.junos_config:
        lines: "{{ config.splitlines() }}"
      when: ansible_network_os == 'junos'

