---
- name: Global configuration
  hosts: cisco:arista:nxos:juniper
  gather_facts: True
  tasks:
    - name: Global config
      ansible.builtin.set_fact:
        config: "{{ lookup('template', 'templates/{{ ansible_network_os }}/global.j2') }}"

    - name: View the generated configuration
      ansible.builtin.debug:
        var: config.splitlines()

    - name: Global config
      vars:
          # cli_config requires network_cli (Juniper defaults to netconf in inventory)
          ansible_connection: network_cli
      ansible.netcommon.cli_config:
        config: "{{ config }}"

#- name: Global configuration
#  hosts: juniper
#  gather_facts: False
#  tasks:
#    - name: Global config
#      vars:
#          # cli_config requires network_cli
#          ansible_connection: network_cli
#      ansible.netcommon.cli_config:
#        config: "{{ lookup('template', 'templates/{{ ansible_network_os }}/global.j2') }}"
#      tags: juniper
