---
- name: Testing collections
  hosts: cisco1
  gather_facts: False
  collections:
    - clay584.genie

  tasks:
    - learn_genie:
        host: "{{ ansible_host }}"
        port: 22
        protocol: ssh
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        os: ios
        feature: interface
      register: output

    - debug:
        var: output
