---
- name: BGP configuration
  hosts: cisco1
  gather_facts: False
  tasks:
    # cisco.ios.ios_bgp was removed in Ansible 10
    # ios_bgp_global is an alternative/replacement module to use
    - name: Testing BGP configuration
      cisco.ios.ios_bgp_global:
        config:
          as_number: 42
          bgp:
            router_id:
              address: 10.220.88.20
            log_neighbor_changes: true
          # ios_bgp_global syntax change in version >= 9.0.0
          # neighbor -> neighbors
          # address -> neighbor_address
          neighbors:
            - neighbor_address: 10.220.88.38
              remote_as: 44
          networks:
            - address: 192.0.2.0
              netmask: 255.255.254.0
          timers:
            keepalive: 300
            holdtime: 360
            min_holdtime: 360
        state: merged

