---
- name: Exercise 3c
  hosts: localhost
  gather_facts: False
  tasks:
    - debug:
        var: ansible_host
- name: Exercise 3c - Another Play
  hosts: cisco
  gather_facts: False
  tasks:
    - debug:
        var: ansible_connection
    - debug:
        var: ansible_host
