- name: Retrieve space available in bytes (returns 'available_space' variable)
  ansible.builtin.import_role:
    name: file_operations
    tasks_from: available_space

- name: Verify sufficent space on device to store image file.
  ansible.builtin.assert:
    that:
      - available_space | int > primary_image.size + extra_space
    success_msg: "{{ dest_filesystem }} has sufficient space for image file."
