- name: Obtain current 'boot system' values (after changes)
  cisco.ios.ios_command:
    commands: "show run | inc boot.system.*bin"
  register: boot_output

- name: Process Boot Variable
  ansible.builtin.set_fact:
    boot_var: "{{ boot_output.stdout_lines[0] }}"

- name: Display the current boot section
  ansible.builtin.debug:
    var: boot_var

