- name: Obtain current 'boot system' values (before changes)
  ansible.builtin.import_tasks: current_bootsystem.yml

- name: Prompt to continue
  ansible.builtin.pause: 
    prompt: |

      >>>>>>>>>>>>>>>>>>
      You are about to change the boot variable on the device.

      Press "<cntr-c>" and then "a" to abort.

      Press return to continue.
      >>>>>>>>>>>>>>>>>>

- name: Update 'boot system' to new value
  cisco.ios.ios_config:
    lines:
      - no boot system
      - "boot system flash {{ primary_image.name }}"
      # - "boot system flash {{ backup_image.name }}"
    # Always save the changes to startup-config
    save_when: always
    # Force Ansible to always push all of the lines
    match: none
    backup: True
