---
# genie filter
# textfsm filter1 (parse_cli_textfsm)
# ntc_parse
# parse_genie
# regex filters

- name: Test lookups
  hosts: local
  vars:
    number: "22"
    my_dict:
      key1: val1
      key2: val2
      key3: val3
      key4: val4

  tasks:
#    - debug:
#        var: number
#      when: number | int == 22

#    - debug:
#        msg: "{{ my_dict | to_nice_yaml(indent=4) }}"

#    - debug:
#        msg: "{{ my_dict | to_nice_json(indent=4) }}"

#    - set_fact:
#        data: "{{ lookup('file', 'ip_addresses.yml') | from_yaml }}"

#    - debug:
#        var: data.ip_addresses.la

#    - set_fact:
#        locations: "{{ lookup('file', 'locations.json') | from_json }}"
#
#    - debug:
#        var: locations["seattle"]

    - name: Default value
      debug:
        msg: "{{ unknown_var | default('Hello') }}"

    - name: touch files with an optional mode
      file:
        dest: "{{ item.path }}"
        state: touch
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - path: foo.txt
        - path: bar.txt
        - path: baz.txt
          mode: "0444"

