---
- name: Simple Playbook
  hosts: servers
  vars:
    user: candor
    virtualenv: "/home/{{ user }}/VENV/test_venv"

  tasks:
    - ansible.builtin.ping:

    - ansible.builtin.debug:
        msg: Hello World

    - name: Install Netmiko into virtual environment
      ansible.builtin.pip:
        name: netmiko
        version: 4.6.0
        virtualenv: "{{ virtualenv }}"
      become: true
      become_user: "{{ user }}"
