---
- name: Exercise2
  hosts: arista
  gather_facts: False
  tasks:
    - block:
        - name: Attempt configuration using an invalid password
          vars:
            ansible_ssh_pass: "foobar"
          arista.eos.eos_config:
            lines:
              - "ip name-server {{ dns_server1 }}"
              - "ip name-server {{ dns_server2 }}"

      rescue:
        - name: Try configuration again in rescue-block
          vars:
            # Use environment variable to avoid checking password in.
            ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
          arista.eos.eos_config:
            lines:
              - "ip name-server {{ dns_server1 }}"
              - "ip name-server {{ dns_server2 }}"

