- name: Show interface configuration
  hosts: arista5:nxos1
  gather_facts: False
  tasks:
    - name: Show interface config (eos)
      arista.eos.eos_command:
        commands:
          - show run int Ethernet6
          - show run int Ethernet7
      register: output
      tags: eos
      when: "ansible_network_os == 'eos'"

    - ansible.builtin.debug:
        var: output["stdout_lines"]
      tags: eos
      when: "ansible_network_os == 'eos'"

    - name: Show interface config (nxos)
      cisco.nxos.nxos_command:
        commands:
          - show run int Ethernet1/3
          - show run int Ethernet1/4
      register: output
      tags: nxos
      when: "ansible_network_os == 'nxos'"

    - ansible.builtin.debug:
        var: output["stdout_lines"]
      tags: nxos
      when: "ansible_network_os == 'nxos'"

    - name: switchport config
      cisco.nxos.nxos_config:
        parents: "interface {{ item }}"
        lines:
          - switchport
      tags: nxos_cfg
      when: "ansible_network_os == 'nxos'"
      loop:
        - Ethernet1/3
        - Ethernet1/4
