---
- name: RegEx Example3
  hosts: cisco5
  gather_facts: False

  tasks:
    - name: Executing command
      ios_command:
        commands: show version
      register: output

    - set_fact:
        output: "{{ output.stdout[0] }}"

    - debug:
        msg: "{{ output.splitlines() }}"

    - name: Show Version (return capture group1)
      debug:
        msg: "{{ output | regex_search('^Processor board ID (\\S+).*$', '\\1', multiline=True) }}"

    - name: Show Version (return capture group-named)
      debug:
        msg: "{{ output | regex_search('^Processor board ID (?P<serial_num>\\S+).*$', '\\g<serial_num>', multiline=True) }}"

