---
- name: Missing library
  hosts: cisco1
  gather_facts: False
  tasks:
    - name: Missing library
      vars:
        ansible_connection: local
      napalm.napalm.napalm_get_facts:
        filter: "arp_table"

    - ansible.builtin.debug:
        var: napalm_arp_table
