---

- name: NX-OS Full Config Replace
  hosts: nxos2
  gather_facts: False
  tasks:
    - napalm_install_config:
        replace_config: True
        commit_changes: True
        config_file: "CFGS/{{ inventory_hostname }}-default.txt"
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
        optional_args:
            port: 8443
