---
- name: Configure IP address and ping (NX-OS)
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Ensure interface set to routed mode
      cisco.nxos.nxos_interfaces:
        config:
          - name: "{{ intf_name }}"
            enabled: True
            mode: layer3
        state: merged

    - name: Configure IPv4 Address
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: "{{ intf_name }}"
            ipv4:
              - address: "{{ intf_address }}/{{ intf_netmask }}"
        state: merged

    - name: Ping across interfaces
      ansible.netcommon.net_ping:
        dest: "{{ peer_ip }}"
      register: output

    - name: Verify at least four ping responses received
      ansible.builtin.assert:
        that:
          - output.packets_rx >= 4
