---
- name: Exercise 5
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Generate interface configuration
      ansible.builtin.template:
        src: interfaces.j2
        dest: "./CFGS/{{ inventory_hostname }}/01-{{ inventory_hostname }}-intf.txt"

    - name: Generate BGP configuration
      ansible.builtin.template:
        src: bgp.j2
        dest: "./CFGS/{{ inventory_hostname }}/02-{{ inventory_hostname }}-bgp.txt"

    - name: Assemble the two parts into one configuration change file
      ansible.builtin.assemble:
        src: "./CFGS/{{ inventory_hostname }}/"
        dest: "./CFGS/{{ inventory_hostname }}-config.txt"
